[book]
authors = ["Team viridIT <https://viridit.com/>"]
language = "en"
multilingual = false
src = "src"
title = "vBook - The vSMTP reference book"

[output.html]
git-repository-url = "https://github.com/ViridIT/vSMTP"
edit-url-template = "https://github.com/ViridIT/vBook"
curly-quotes = true

[output.html.fold]
enable = true
