name: checks

on:
  pull_request:
    branches:
      - "next"

name: Check markdown files for broken links
jobs:
  markdown-link-check:
    name: Check markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown links check
        uses: ruzickap/action-my-markdown-link-checker@v1