name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - next

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SITE_SSH_HOST }}
          username: ${{ secrets.SITE_SSH_USERNAME }}
          key: ${{ secrets.SITE_SSH_KEY }}
          passphrase: ${{ secrets.SITE_SSH_PASSPHRASE }}
          script: |
            sudo su - mdbook && cd vBook && git checkout next && git pull && mdbook build && exit
            sudo cp -Rf /home/mdbook/vBook/book/* /var/www/vbook/next
