name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - next

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SITE_SSH_HOST }}
          username: ${{ secrets.SITE_SSH_USERNAME }}
          key: ${{ secrets.SITE_SSH_KEY }}
          passphrase: ${{ secrets.SITE_SSH_PASSPHRASE }}
          script: |
            sudo su - mdbook -c 'cd vBook && git checkout next && git pull && mdbook build'
            sudo cp -Rf /home/mdbook/vBook/book/* /var/www/vbook/next
            sudo su - mdbook -c 'cd vSMTP && git checkout develop && git pull && RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --workspace --no-deps --all-features'
            sudo cp -Rf /home/mdbook/vSMTP/target/doc/* /var/www/vbook/next/docrs
